name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Open SSH debug session
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 60
      # - uses: actions/checkout@v4
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
